### ISSUE TITLE
`parse_result()`

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/punkapi#1]
Create a function that turns an API result to a data.frame. 

```r
res <- httr::GET(
  "https://api.punkapi.com/v2/beers/1"
)
httr::content(res)[[1]] # <- Turn this into a data.frame with one row
```

**Comment by flenartz** [comment]
Première tentative pushée au lieu de faire un pull request et donc je ne sais pas si tu es assigné en tant que reviewer ...

**Comment by ColinFay** [comment]
@flenartz est-ce que tu as ouvert une Pull Request ?

https://github.com/ThinkR-open/punkapi/compare

**Comment by flenartz** [comment]
J'ai voulu le faire après mais j'ai eu une erreur 404, je ré-essaie
